// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuo0d0x2749zVLCDl_lbmB_U6MkBYoL5c',
    appId: '1:501404852685:web:c3aba5358474bbef2de484',
    messagingSenderId: '501404852685',
    projectId: 'parking-auth-3113b',
    authDomain: 'parking-auth-3113b.firebaseapp.com',
    storageBucket: 'parking-auth-3113b.firebasestorage.app',
    measurementId: 'G-CTY6BDNG9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmxA0vrRKQk5ZLErN9GLO1EJNtEqonDFo',
    appId: '1:501404852685:android:d50336655685f5942de484',
    messagingSenderId: '501404852685',
    projectId: 'parking-auth-3113b',
    storageBucket: 'parking-auth-3113b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUps0JkRMrxHAVjHWmr7DCnyZiwOjzf7c',
    appId: '1:501404852685:ios:3f4d728cbbb2a42d2de484',
    messagingSenderId: '501404852685',
    projectId: 'parking-auth-3113b',
    storageBucket: 'parking-auth-3113b.firebasestorage.app',
    iosBundleId: 'com.example.project8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUps0JkRMrxHAVjHWmr7DCnyZiwOjzf7c',
    appId: '1:501404852685:ios:3f4d728cbbb2a42d2de484',
    messagingSenderId: '501404852685',
    projectId: 'parking-auth-3113b',
    storageBucket: 'parking-auth-3113b.firebasestorage.app',
    iosBundleId: 'com.example.project8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuo0d0x2749zVLCDl_lbmB_U6MkBYoL5c',
    appId: '1:501404852685:web:05f5b2690c30bd262de484',
    messagingSenderId: '501404852685',
    projectId: 'parking-auth-3113b',
    authDomain: 'parking-auth-3113b.firebaseapp.com',
    storageBucket: 'parking-auth-3113b.firebasestorage.app',
    measurementId: 'G-2F39EFLM5D',
  );

}